# Generated by Django 5.1 on 2024-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('danger', 'danger'), ('sucess', 'sucess'), ('primary', 'primary'), ('info', 'info')], default=('sucess', 'sucess'), max_length=10),
        ),
    ]
