# Generated by Django 5.1 on 2024-09-27 09:37

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default=courses.models.course_color, max_length=10),
        ),
    ]
