# Generated by Django 5.1 on 2024-09-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
    ]
