# Generated by Django 5.1 on 2024-09-28 19:08

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('danger', 'червоний'), ('primary', 'синій'), ('success', 'зелений'), ('info', 'голубий'), ('dark', 'чорний')], default=courses.models.course_color, max_length=10),
        ),
    ]
