# Generated by Django 5.1 on 2024-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='value',
        ),
    ]
