# Generated by Django 5.1 on 2024-10-03 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_grade_grade_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
